[package]
name = "codecache"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29"
ratatui = "0.29"
tui-widget-list = "0.13"
syntect = "5.3"
ansi-to-tui = "7.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"